[package]
name = "isolator"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.6.1"
prost = "0.9.0"
futures = "0.3.17"
futures-core = "0.3.17"
futures-util = "0.3.17"
async-stream = "0.3.2"
deno_core = "0.107.0"
tokio = { version = "1.13", features = ["rt", "macros", "sync", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.6.0"
deno_core = "0.107.0"
